title: Jesse Dunietz
#subtitle: AI researcher, science communicator
description: AI researcher/consultant, science communication trainer, science writer
author: Jesse Dunietz
email: yavyash@gmail.com
avatar: assets/images/avatar.jpg
avatar_roundness: 20 # Can be 0 (sharp square) to 50 (circle); anything above is equivalent to 50.

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jessedunietz.com" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url: https://twitter.com/jdunietz
linkedin_url: https://www.linkedin.com/in/jessedunietz/
github_url: https://github.com/duncanka/
google_scholar_url: https://scholar.google.com/citations?user=axPsqwQAAAAJ&hl=en

social_newtabs: true
social_tooltips: true

# Google Analytics Tracking ID goes here:
google_analytics:

remote_theme: duncanka/jekyll-theme-prologue
collections: [sections]

